### ISSUE TITLE
Applications ran by a bindsym to i3-input, are frozen until unfocused and refocused.

### ISSUE THREAD

**Issue by geo909** [i3/i3#2612]
Output of `i3 --moreversion 2>&- || i3 --version`:

```
Binary i3 version:  4.13 (2016-11-08) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.13 (2016-11-08) (pid 10285) abort…)
Loaded i3 config: /home/jorge/.config/i3/config (Last modified: Mon 19 Dec 2016 11:26:53 PM EST, 2768 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

URL to a logfile as per http://i3wm.org/docs/debugging.html:

http://logs.i3wm.org/logs/5728885882748928.bz2

```

**What I did:**

I have the following line in my config file ($mod is my alt key):
`bindsym $mod+y exec i3-input -F 'exec xterm'`

When I press Alt+y, an empty i3-input window pops up. I write something random and press enter. 
This just runs xterm regardless of the the input. Mind that this is a useless example to demonstrate the problem, so please bare with me. The command that I was using originally is unecessary complicated to post here.

**What I saw:**

An xterm window opens but it's frozen, that is, although it's focused I cannot type anything

**What I expected instead:**

Xterm should be responsive, that is, I should be able to type in it right away.

**Some more details:**

1. **This issue was not present in 4.12-1**
2. The issue seems to be with bindsym. This is because if I run `xterm` from dmenu or a terminal, there are no issues
3. I can reproduce the problem with a minimal config file (empty, apart from the problematic bindsym, and the $mod key set)
4. The same problem is present if I run something other than xterm, like a text editor for instance.

**Comment by stapelberg** [comment]
Does it help to use `bindsym --release`?

**Comment by Airblader** [comment]
Can you reproduce this on the current `next` branch? It may have been fixed with #2598

**Comment by geo909** [comment]
@Airblader Thanks, indeed I don't have this problem with the next branch

(@stapelberg I guess not relevant anymore but `bindsym --release` did not fix it)

Many thanks again guys.
