### ISSUE TITLE
Crash on parsing for_window config

### ISSUE THREAD

**Issue by KJoke70** [i3/i3#3406]
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

Adding the line

    for_window [class="__focused__" instance="virt-manager"] exec xdotool mousemove 0 0

will crash i3 upon loading the config.

## Expected Behavior

Startup with nagbar notifying me about an error in my config.

## Reproduction Instructions

Add `for_window [class="__focused__" instance="virt-manager"] exec xdotool mousemove 0 0` to the config and restart in-place.

EDIT:
Adding `for_window [class="__focused__"] floating enable` (or any other command) will also result in a crash.

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: 
Binary i3 version:  4.15-258-g18f705a9 (2018-09-14, branch "next") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.15-258-g18f705a9 (2018-09-14, branch "next") (pid 4526)
Loaded i3 config: /home/martin/.config/i3/config (Last modified: Sat 15 Sep 2018 01:09:12 AM CEST, 275 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
</pre>

Default config with Alt as $mod and the abovementioned line added near the end:
https://pastebin.com/bbySQTJu

<pre>
Logfile: No logfile since it crashes on start
Backtrace: `No stack.`
</pre>

<pre>
- Linux Distribution & Version: Arch Linux, 4.18.7-arch1-1-ARCH
- Are you using a compositor (e.g., xcompmgr or compton): None
</pre>

**Comment by orestisf1993** [comment]
Thanks!

What you are trying to do might not work correctly because of #1573 but the crash should be fixed.

**Comment by KJoke70** [comment]
The PR fixes the crash on startup but it will still crash if a window matching the criteria is in focus when restarting. 

For example if I add `for_window [class="__focused__" instance="virt-manager"] exec xdotool mousemove 0 0` to the config, open virt-manager and then restart in-place it will crash.

**Comment by orestisf1993** [comment]
Thanks!

**Comment by KJoke70** [comment]
Did a quick test and this seems to work!
